version: "3.9"

services:
  backend:
    build:
      dockerfile: ./backend.Dockerfile
      context: .
    container_name: web-whisper-backend
    environment:
      CUT_MEDIA_SECONDS: "10"
  
  whisper:
    build:
      dockerfile: ./frontend.Dockerfile
      context: .
      args:
        - DOMAIN_NAME=localhost:3000
        - ALLOW_FILE_UPLOADS=true
    container_name: web-whisper
    ports:
      - "127.0.0.1:3000:80"