version: "3.9"

services:
  backend:
    build:
      dockerfile: ./backend.Dockerfile
      context: .
    container_name: web-whisper-be
  
  frontend:
    build:
      dockerfile: ./frontend.Dockerfile
      context: .
    container_name: web-whisper-fe
    ports:
      - "127.0.0.1:3000:443"